image: "python:latest"

stages:
    - test
    - deploy

pip_deploy:
    stage: deploy
    script:
        - pip install twine wheel
        - python setup.py sdist bdist_wheel
        - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
    only:
        - tags

pytest:
    stage: test
    script:
        - pip install requests pytest
        - pytest

flake8:
    stage: test
    script:
        - pip install flake8 flake8-annotations
        - flake8
