depends_on:
    - lint
    - test
    - typecheck

steps:
    pip_deploy:
        image: python:latest
        commands:
            - pip install twine build
            - python -m build
            - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
        environment:
            PYPI_USERNAME:
                from_secret: PYPI_USERNAME
            PYPI_PASSWORD:
                from_secret: PYPI_PASSWORD

when:
    event: release
    branch: master
