matrix:
    PYTHON_IMAGE:
        - python:3.8
        - python:3.9
        - python:3.10
        - python:3.11
        - python:3.12
        - python:3.13
        - pypy:latest

steps:
    pytest:
        image: ${PYTHON_IMAGE}
        commands:
            - pip install -r requirements-test.txt
            - pytest
