matrix:
    PYTHON_IMAGE:
        - python:3.8
        - python:3.9
        - python:3.10
        - python:3.11
        - pypy:latest

pipeline:
    pytest:
        image: ${PYTHON_IMAGE}
        commands:
            - pip install pytest pytest-cov requests requests-mock
            - pytest -v --cov=minecraft_launcher_lib
