contact_links:
  - name: Documentation
    url: https://minecraft-launcher-lib.readthedocs.io
    about: Take a look at the official documentation. before creating a Issue. It may help your with your Problem.
