name: 'Repo Lockdown'

on:
  pull_request_target:
    types: opened

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          pr-comment: "This Repo is just a mirror of the [Codeberg Repo](https://codeberg.org/JakobDev/minecraft-launcher-lib). PRs arren't acceptet here. Please make a PR against the Codeberg Repo. It works the same Way as in GitHub. You can use your GitHub Account to login into Codeberg."
